import Image from "next/image";
import { twMerge } from "tailwind-merge";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import { useEffect, useState } from "react";
import { Input } from "@/components/ui/input";
import { useSelector } from "react-redux";
import { RootState } from "@/core/store/store";
import { userSecurityService } from "@/core/services/auth/userSecurity.service";
import { useToast } from "@/hooks/use-toast";

interface QrModalInterface {
  open: boolean;
  setOpen: (open: boolean) => void;
  qrCode: string;
  code: string;
}

const texts = {
  verifyWithPasskey: "Link an Authenticator",
  verificationMessage: "Scan this QR code in the authenticator app",
  button: "Next",
  qrMessage:
    "If you are unable to scan the QR code, please enter this code manually into the app.",

  passkeysNotAvailable: "My Passkeys Are Not Available",
  phoneNumberVerification: "Verify Authenticator",
  enterCodeMessage: "Enter the 6-digit code generated by the Authenticator App",
  phoneVerificationCode: "Authenticator App Code",
  submit: "Submit",
};

export const QrModal = (props: QrModalInterface) => {
  const { open, setOpen } = props;
  const [authenticator, setAuthenticator] = useState(false);
  const [value, setValue] = useState("");
  const [disabled, setDisabled] = useState(true);

  const handleChange = (e: any) => {
    setValue(e.target.value);
  };

  const handleCopyClick = (textToCopy: string) => {
    navigator.clipboard
      .writeText(textToCopy)
      .then(() => {
        console.log("Text copied to clipboard: ", textToCopy);
      })
      .catch((err) => {
        console.error("Could not copy text: ", err);
      });
  };

  const sendActivation = (e: any) => {
    e.preventDefault();
    userSecurityService.EnableGoogleAuthenticator(value).then((res) => {
      if (res.success) {
        toast?.open('Authenticator aktif edildi.', 'check-circle', '', 'text-red')
        setOpen(false);
      } else {
        toast?.open(res.messageList[0].message, 'check-circle', '', 'text-red')
      }
    });
  }
  const toast = useToast();

  const handlePasteClick = async () => {
    try {
      const textFromClipboard = await navigator.clipboard.readText();
      setValue(textFromClipboard);
    } catch (err) {
      console.error("Failed to read clipboard contents: ", err);
    }
  };

  return (
    <>
      <Modal
        open={open}
        setOpen={setOpen}
        showCloseButton
        className="md:w-[425px] md:max-w-[80vw] w-full md:h-[580px] h-full max-w-[none]"
        showBackButton={authenticator ? true : false}
        onBackButtonClick={() => setAuthenticator(false)}
      >
        {!authenticator ? (
          <div className="flex flex-col md:px-4">
            <div className="sm:text-[32px] text-left font-semibold sm:leading-[40px] text-[28px] leading-[36px] text-black-100 dark:text-white-100 mb-4">
              {texts.verifyWithPasskey}
            </div>
            <div className="text-base text-gray-300 dark:text-gray-100 mb-2">
              {texts.verificationMessage}
            </div>
            <div className="flex justify-center flex-col items-center my-8">
              <Image
                src={props.qrCode}
                width={160}
                height={160}
                alt="QR Code"
                className="mb-8"
              />
              <div className="py-2.5 flex items-center mb-2">
                <div className="flex-1 text-base text-gray-300 dark:text-gray-100 font-semibold">
                  {props.code}
                </div>
                <div
                  onClick={() => {
                    handleCopyClick(props.code);
                  }}
                >
                  <Icon className="ml-1" name="copy" size="16" />
                </div>
              </div>
              <div className="text-sm text-gray-300 text-center dark:text-gray-100 mb-2">
                {texts.qrMessage}
              </div>
            </div>

            <Button
              appearance="primary"
              className="w-full h-12 flex items-center justify-center rounded-xl font-normal"
              onClick={() => setAuthenticator(true)}
            >
              {texts.button}
            </Button>
          </div>
        ) : (
          <div className="flex flex-col md:px-4">
            <div className="sm:text-[32px] text-left font-semibold sm:leading-[40px] text-[28px] leading-[36px] text-black-100 dark:text-white-100 mb-4">
              {texts.phoneNumberVerification}
            </div>
            <div className="text-base text-gray-300 dark:text-gray mb-8">
              {texts.enterCodeMessage}
            </div>
            <label
              htmlFor="code"
              className="text-sm text-gray-300 dark:text-gray"
            >
              {texts.phoneVerificationCode}
            </label>
            <Input
              id="code"
              className="h-12 rounded-[10px] w-full mt-1"
              value={value}
              onChange={handleChange}
              pasteMode={true}
              onPasteClick={handlePasteClick}
            />

            <Button
              appearance="primary"
              onClick={sendActivation}
              className={twMerge(
                "w-full h-12 flex items-center justify-center rounded-xl font-normal mt-6 mb-4",
                // value.length == 6 ? '': 'disabled' && "cursor-not-allowed opacity-30"
              )}
            >
              {texts.submit}
            </Button>
          </div>
        )}
      </Modal>
    </>
  );
};
